#!/bin/bash -e

SCRIPT_BASE="${SCRIPT_BASE:-$(dirname "${BASH_SOURCE[0]}")}"

WSROOT="${IAC_DEPL_COMP}"
WSROOT="${WSROOT:-$(iac dir comp)}"
WSROOT="${WSROOT:-$SCRIPT_BASE/..}"

#LSROOT="${IAC_LS_ROOT:-$(iac dir)}"

CONFIG_DIR="${IAC_DEPL_INST:-$WSROOT}"
STATE_DIR="${IAC_DEPL_STATE:-$WSROOT}"
COMP_DIR="${IAC_DEPL_COMP:-$WSROOT}"
WORK_DIR="${IAC_DEPL_GEN:-$WSROOT}"

GEN_DIR="$CONFIG_DIR/gen"

TMPL="$WSROOT/export-template.yml" 
if [ ! -f "$TMPL" ]; then
  TMPL="$WSROOT/export.yml" 
fi
if [ ! -f "$TMPL" ]; then
  TMPL="$WSROOT/helper/export.yml" 
fi

ACTION_create_exports()
{
   
  if [ -f "$TMPL" ]; then
    if [ -n "$IAC_ACTION_CREATE_MANIFEST" ]; then
      "$IAC_ACTION_CREATE_MANIFEST" "$@"
    else
      echo "---"
    fi | spiff merge "$TMPL" - "$1"
  else
    if [ -n "$IAC_ACTION_CREATE_MANIFEST" ]; then
      "$IAC_ACTION_CREATE_MANIFEST" "$@"
    else
      cat "$1"
    fi | yaml2json | jq .exports | spiff merge -
  fi
}


if [ -z "$IAC_QUIET" ]; then
  echo "--> action create_exports $1" >&2
fi
ACTION_create_exports "$@"
