#!/bin/bash -e

PLUGIN="$(dirname "$0")/.."

ACTION_create_exports()
{
  if [ -n "$IAC_ACTION_CREATE_MANIFEST" ]; then
    "$IAC_ACTION_CREATE_MANIFEST" "$@"
  else
    cat "$1"
  fi | yaml2json | jq .exports | spiff merge -
}


if [ -z "$IAC_QUIET" ]; then
  echo "--> action create_exports $1" >&2
fi
ACTION_create_exports "$@"
